In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import sklearn
import matplotlib
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("encoded")

In [3]:
df.head()

Unnamed: 0             name         rollno  \
0           0  Naman Chaudhary     1803211033   
1           1   Utsav Mehrotra     1803211058   
2           2     Akshat Atray     1803211003   
3           3    Shivam Sharma  1900321290059   
4           4     Aditya saini  2000321530010   

                                              branch  year  gender  age  pt  \
0                                               CEIT     4       1   20   1   
1                                               CEIT     4       1   21   1   
2                                               CEIT     4       1   21   1   
3                                               CEIT     3       1   20   1   
4  Computer Science( CS- AI/ML, CS - Data Science...     2       1   20   1   

   st  ppl  ...  sgpa  personality  behaviour  decison  adaptablilty  life  \
0   8    1  ...     3            4          4        3             3     3   
1   2    3  ...     2            3          5        1             5     5   
2  11    1  ...     2            4          5        2             5     4   
3   7    2  ...     3            4          4        4             3     2   
4   6    1  ...     2            4          5        3             5     4   

   hobby  hstudy  match  Total_personality_score  
0      4       0      1                      3.4  
1      1       0      1                      3.8  
2      0       0      1                      4.0  
3      0       0      1                      3.4  
4      4       2      1                      4.2  

[5 rows x 25 columns]

In [4]:
df.columns

Index(['Unnamed: 0', 'name', 'rollno', 'branch', 'year', 'gender', 'age', 'pt',
       'st', 'ppl', 'spl', 'c_rate', 'w_rate', 'certified', '12', 'sgpa',
       'personality', 'behaviour', 'decison', 'adaptablilty', 'life', 'hobby',
       'hstudy', 'match', 'Total_personality_score'],
      dtype='object')

In [5]:
del df['Unnamed: 0']

In [6]:
df

name         rollno  \
0    Naman Chaudhary     1803211033   
1     Utsav Mehrotra     1803211058   
2       Akshat Atray     1803211003   
3      Shivam Sharma  1900321290059   
4       Aditya saini  2000321530010   
..               ...            ...   
323     Sanskar garg  2000320120151   
324    Sumit Jaiswal  2000320120176   
325     Kapil Panwar  2000320120093   
326   Santosh Pandit  2000320120152   
327        Dev Tayal  2000320120070   

                                                branch  year  gender  age  pt  \
0                                                 CEIT     4       1   20   1   
1                                                 CEIT     4       1   21   1   
2                                                 CEIT     4       1   21   1   
3                                                 CEIT     3       1   20   1   
4    Computer Science( CS- AI/ML, CS - Data Science...     2       1   20   1   
..                                                 ...   ...     ...  ...  ..   
323  Computer Science( CS- AI/ML, CS - Data Science...     2       1   19  14   
324  Computer Science( CS- AI/ML, CS - Data Science...     2       1   20  12   
325  Computer Science( CS- AI/ML, CS - Data Science...     2       1   20   1   
326  Computer Science( CS- AI/ML, CS - Data Science...     2       1   19   1   
327  Computer Science( CS- AI/ML, CS - Data Science...     2       1   17   3   

     st  ppl  spl  ...  sgpa  personality  behaviour  decison  adaptablilty  \
0     8    1    3  ...     3            4          4        3             3   
1     2    3    1  ...     2            3          5        1             5   
2    11    1    3  ...     2            4          5        2             5   
3     7    2    3  ...     3            4          4        4             3   
4     6    1    3  ...     2            4          5        3             5   
..   ..  ...  ...  ...   ...          ...        ...      ...           ...   
323   3    2    1  ...     2            4          5        5             4   
324   5    2    1  ...     3            3          3        3             3   
325   2    2    3  ...     2            1          4        3             3   
326   3    2    3  ...     2            3          4        3             3   
327   1    1    3  ...     1            5          3        1             2   

     life  hobby  hstudy  match  Total_personality_score  
0       3      4       0      1                      3.4  
1       5      1       0      1                      3.8  
2       4      0       0      1                      4.0  
3       2      0       0      1                      3.4  
4       4      4       2      1                      4.2  
..    ...    ...     ...    ...                      ...  
323     2      0       0      0                      4.0  
324     3      1       0      0                      3.0  
325     3      1       1      0                      2.8  
326     3      1       0      1                      3.2  
327     3      0       0      0                      2.8  

[328 rows x 24 columns]

In [7]:
technical = df[["pt","st","ppl","spl","c_rate","w_rate","certified","sgpa","12"]]

In [8]:
technical

pt  st  ppl  spl  c_rate  w_rate  certified  sgpa  12
0     1   8    1    3       3       3          1     3   3
1     1   2    3    1       3       4          0     2   3
2     1  11    1    3       4       5          1     2   2
3     1   7    2    3       2       3          0     3   2
4     1   6    1    3       3       4          0     2   2
..   ..  ..  ...  ...     ...     ...        ...   ...  ..
323  14   3    2    1       1       1          1     2   2
324  12   5    2    1       3       3          0     3   3
325   1   2    2    3       1       3          0     2   3
326   1   3    2    3       3       2          0     2   2
327   3   1    1    3       2       1          0     1   1

[328 rows x 9 columns]

In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as pltu
from mpl_toolkits.mplot3d import Axes3D
from sklearn_extra.cluster import KMedoids

In [10]:
num_digits=13
models = [
     (
         KMedoids(metric="manhattan", n_clusters=num_digits, 
         init="heuristic", max_iter=2),"Manhattan metric",
     ),
     (
         KMedoids(metric="euclidean", n_clusters=num_digits,  
         init="heuristic", max_iter=2),"Euclidean metric",
     ),
     (KMedoids(metric="cosine", n_clusters=num_digits, init="heuristic", 
      max_iter=2), "Cosine metric", ),
 ] 

In [11]:
technical.shape

(328, 9)

In [12]:
num_cols, num_rows,red_data = 9,328,technical
second_model = []
for i, (model, description) in enumerate(models):
    Z = model.fit(technical)
    second_model.append(Z.labels_)
    print(Z.labels_)

[ 5  3  5  5  2  2  4  0  7 11  9 11 11  3  8  9  9  6  9  7  5  9  9  7
  9  1  2  2  7  3  3  2  3  4  1  2  9  9  2  4  9  9  8  6  9  6  9  0
  6  8 11  6  8  8  3  0 10  5  3 10  6  5  3  2  5  8  1  7 11  3  2  0
  9 12 12  3  4  3  9  3  9  6  3  1  6 10  2  4  1  4  7  4  4  0  8  3
  6  6  1 10  9  7 10  1  3 10  9  3  9  1  3  5  9  3  2  0  3  2  9  7
  1  6 10  5  1  8  1  2  8  8  9  8  2  5  5  3 11 11  6  2  2 11  3  3
  2  7  5  5  5  5 10  6  9  9  3  2  4  0  0  0 12  8  0 11  3  7  7  7
  4  0  6  1  2  2  0  8  5  9  7  0  9  0  0  5  3  1  7  7  7  2  9  0
  3 12 11 10  5  2  8 10  2  1  9  1  9  5  6 12  1  5  0  5 12  2  1  8
 12  3 10  0  2  8 11  0 10  3  6  3  0  8  5  0 11  9  8 10  3  7  6  3
  5  7  7  0  9  3  6  2  9  8  3  0  6  0  7  3  8  7  0  3  9  0  7 10
  0  9  9  3  3  3  2  2  2  5  5  6  9  6  0 11  0  2  5  3 12  3  6  6
  6  6  9 11  7  6  9  9  0  3  7  7  6  3  5  7  9  4  2  4  3  0  1  2
  0  9  7  0  2  3  2  3 11  0  7  7  6  3  3 11]
[

c:\users\utkar\pycharmprojects\pythonproject\venv\lib\site-packages\sklearn_extra\cluster\_k_medoids.py:275: UserWarning: Cluster 12 is empty! self.labels_[self.medoid_indices_[12]] may not be labeled with its corresponding cluster (12).
  warnings.warn(
c:\users\utkar\pycharmprojects\pythonproject\venv\lib\site-packages\sklearn_extra\cluster\_k_medoids.py:243: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn(
c:\users\utkar\pycharmprojects\pythonproject\venv\lib\site-packages\sklearn_extra\cluster\_k_medoids.py:243: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn(
c:\users\utkar\pycharmprojects\pythonproject\venv\lib\site-packages\sklearn_extra\cluster\_k_medoids.py:243: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warning

In [13]:
model = KMedoids(metric="euclidean", n_clusters=13,  
         init="heuristic", max_iter=2)

In [14]:
model.fit(technical)

c:\users\utkar\pycharmprojects\pythonproject\venv\lib\site-packages\sklearn_extra\cluster\_k_medoids.py:243: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn(


KMedoids(max_iter=2, n_clusters=13)

In [15]:
model.predict([[1,1,1,1,1,1,1,1,1]])

array([12], dtype=int64)

In [16]:
Roll=df['rollno']

In [17]:
f=pd.DataFrame(Roll)

In [18]:
f

rollno
0       1803211033
1       1803211058
2       1803211003
3    1900321290059
4    2000321530010
..             ...
323  2000320120151
324  2000320120176
325  2000320120093
326  2000320120152
327  2000320120070

[328 rows x 1 columns]

In [19]:
u=pd.Series(model.labels_)

In [ ]:
f["cluster"]=u

In [ ]:
f.head()

In [ ]:
f.loc[f["cluster"]==5]

In [ ]:
df

In [ ]:
print(df.loc[df["rollno"]=="1900320120011"].columns ,df.loc[df["rollno"]=="1900320120011"].values)

In [ ]:
technical = df[["pt","st","ppl","spl","c_rate","w_rate","certified","sgpa","12"]]

In [ ]:
models[1].predict([1,2,0,1,3,2,0,3,3])

In [ ]:
len(second_model[1])

In [93]:
behaviour=df[["personality","behaviour","decison","adaptablilty","life","hobby","hstudy","match"]]

In [94]:
behaviour

personality  behaviour  decison  adaptablilty  life  hobby  hstudy  match
0              4          4        3             3     3      4       0      1
1              3          5        1             5     5      1       0      1
2              4          5        2             5     4      0       0      1
3              4          4        4             3     2      0       0      1
4              4          5        3             5     4      4       2      1
..           ...        ...      ...           ...   ...    ...     ...    ...
323            4          5        5             4     2      0       0      0
324            3          3        3             3     3      1       0      0
325            1          4        3             3     3      1       1      0
326            3          4        3             3     3      1       0      1
327            5          3        1             2     3      0       0      0

[328 rows x 8 columns]

In [24]:
model2=KMedoids(metric="euclidean", n_clusters=num_digits,  
         init="heuristic", max_iter=2)

In [26]:
model2.fit(behaviour)

c:\users\utkar\pycharmprojects\pythonproject\venv\lib\site-packages\sklearn_extra\cluster\_k_medoids.py:275: UserWarning: Cluster 3 is empty! self.labels_[self.medoid_indices_[3]] may not be labeled with its corresponding cluster (3).
  warnings.warn(
c:\users\utkar\pycharmprojects\pythonproject\venv\lib\site-packages\sklearn_extra\cluster\_k_medoids.py:275: UserWarning: Cluster 6 is empty! self.labels_[self.medoid_indices_[6]] may not be labeled with its corresponding cluster (6).
  warnings.warn(
c:\users\utkar\pycharmprojects\pythonproject\venv\lib\site-packages\sklearn_extra\cluster\_k_medoids.py:243: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn(


KMedoids(max_iter=2, n_clusters=13)

In [27]:
model2.predict([[3,3,3,3,3,1,2,1]])

array([2], dtype=int64)

In [30]:
model2.labels_

array([ 0, 12,  8,  4,  5,  5,  5, 12, 12,  5,  0,  5, 12, 12,  8,  7,  9,
       10,  8,  7,  9,  5,  1,  0,  1,  8,  3,  9, 11,  1,  7,  2,  7,  5,
        4,  1,  7,  4,  1,  5,  1,  2,  7,  9, 12,  0,  0,  8,  5,  5,  7,
        5,  9,  1,  4,  7,  3,  2, 12,  9,  0,  2,  1,  7,  8, 12,  5, 11,
        0,  4, 12,  1,  1,  3,  5,  9, 12,  8,  2,  7,  7,  9,  0,  0,  0,
        4,  4,  5,  5,  3,  4,  5,  2,  7,  0,  2,  9,  9,  4,  3,  5,  0,
        1,  0,  2,  0,  0,  5,  0, 12,  3, 11,  2, 12,  2,  4,  5,  2,  4,
        9,  2,  5,  3,  7,  7,  2,  0,  5, 12,  9,  8,  2,  2,  2,  5,  2,
        4, 11,  7,  2, 12,  8, 12,  8,  0,  1, 12,  1,  4,  8,  7,  7,  0,
        0,  9,  2,  5, 12,  4,  3,  7,  1, 12,  0,  0,  4,  2,  4,  5,  7,
       12,  4,  2,  8,  5,  9, 11, 10,  2,  4,  7, 11, 11,  2,  5, 10,  1,
        4, 11,  9, 10,  0,  0,  7,  5,  7,  2,  9,  0,  4,  7, 12,  8,  4,
        4,  9,  8,  7, 10,  0,  2,  2,  7,  3,  0,  2,  5, 11,  7, 11,  4,
        7,  7,  8,  3,  4

In [31]:
behv=pd.DataFrame(Roll)

In [33]:
u1=pd.Series(model2.labels_)

In [37]:
behv["behv_cluster"]=u1

In [39]:
behv["behv_cluster"].value_counts()

4     47
0     37
5     37
2     36
7     35
12    30
9     27
1     20
8     19
11    19
3     14
10     7
Name: behv_cluster, dtype: int64

In [40]:
behv.loc[behv["behv_cluster"]==2]

rollno behv_cluster
31   2000321530131            2
41   2000321530059            2
57   2000321530077            2
61   2000321530074            2
78   2000321530046            2
92   1900320120051            2
95   2000320120005            2
104  2000320120001            2
112  1900321290063            2
114  2000321530131            2
117     1803211028            2
120  2000321530041            2
125  2000321530032            2
131  2000320120056            2
132  2000321530019            2
133  1900320150001            2
135  2000320120088            2
139  2000321530019            2
155  2000320120078            2
166  2000320120101            2
172  1900321290035            2
178  2000321530064            2
183  2000321530023            2
196  2000320129004            2
210     1803211018            2
211     1803211037            2
215  1900320120011            2
229  1900321290053            2
236  2000321530029            2
240  1900321290045            2
276  2000321530011            2
286   2021B0123005            2
289  2000320120195            2
299  2000320120164            2
306  2000320120177            2
311  2000320120078            2

In [41]:
print(df.loc[df["rollno"]=="1900321290035"].columns ,df.loc[df["rollno"]=="1900321290035"].values)

Index(['name', 'rollno', 'branch', 'year', 'gender', 'age', 'pt', 'st', 'ppl',
       'spl', 'c_rate', 'w_rate', 'certified', '12', 'sgpa', 'personality',
       'behaviour', 'decison', 'adaptablilty', 'life', 'hobby', 'hstudy',
       'match', 'Total_personality_score'],
      dtype='object') [['Himani yadav' '1900321290035' 'CEIT' 3 0 19 3 7 2 3 3 1 0 3 3 3 4 3 4
  3 1 2 0 3.4]]


In [44]:
df

name         rollno  \
0    Naman Chaudhary     1803211033   
1     Utsav Mehrotra     1803211058   
2       Akshat Atray     1803211003   
3      Shivam Sharma  1900321290059   
4       Aditya saini  2000321530010   
..               ...            ...   
323     Sanskar garg  2000320120151   
324    Sumit Jaiswal  2000320120176   
325     Kapil Panwar  2000320120093   
326   Santosh Pandit  2000320120152   
327        Dev Tayal  2000320120070   

                                                branch  year  gender  age  pt  \
0                                                 CEIT     4       1   20   1   
1                                                 CEIT     4       1   21   1   
2                                                 CEIT     4       1   21   1   
3                                                 CEIT     3       1   20   1   
4    Computer Science( CS- AI/ML, CS - Data Science...     2       1   20   1   
..                                                 ...   ...     ...  ...  ..   
323  Computer Science( CS- AI/ML, CS - Data Science...     2       1   19  14   
324  Computer Science( CS- AI/ML, CS - Data Science...     2       1   20  12   
325  Computer Science( CS- AI/ML, CS - Data Science...     2       1   20   1   
326  Computer Science( CS- AI/ML, CS - Data Science...     2       1   19   1   
327  Computer Science( CS- AI/ML, CS - Data Science...     2       1   17   3   

     st  ppl  spl  ...  sgpa  personality  behaviour  decison  adaptablilty  \
0     8    1    3  ...     3            4          4        3             3   
1     2    3    1  ...     2            3          5        1             5   
2    11    1    3  ...     2            4          5        2             5   
3     7    2    3  ...     3            4          4        4             3   
4     6    1    3  ...     2            4          5        3             5   
..   ..  ...  ...  ...   ...          ...        ...      ...           ...   
323   3    2    1  ...     2            4          5        5             4   
324   5    2    1  ...     3            3          3        3             3   
325   2    2    3  ...     2            1          4        3             3   
326   3    2    3  ...     2            3          4        3             3   
327   1    1    3  ...     1            5          3        1             2   

     life  hobby  hstudy  match  Total_personality_score  
0       3      4       0      1                      3.4  
1       5      1       0      1                      3.8  
2       4      0       0      1                      4.0  
3       2      0       0      1                      3.4  
4       4      4       2      1                      4.2  
..    ...    ...     ...    ...                      ...  
323     2      0       0      0                      4.0  
324     3      1       0      0                      3.0  
325     3      1       1      0                      2.8  
326     3      1       0      1                      3.2  
327     3      0       0      0                      2.8  

[328 rows x 24 columns]

In [46]:
df[["rollno","name","pt","st","ppl","spl","c_rate","w_rate","certified","sgpa","12"]].head()

rollno             name  pt  st  ppl  spl  c_rate  w_rate  \
0     1803211033  Naman Chaudhary   1   8    1    3       3       3   
1     1803211058   Utsav Mehrotra   1   2    3    1       3       4   
2     1803211003     Akshat Atray   1  11    1    3       4       5   
3  1900321290059    Shivam Sharma   1   7    2    3       2       3   
4  2000321530010     Aditya saini   1   6    1    3       3       4   

   certified  sgpa  12  
0          1     3   3  
1          0     2   3  
2          1     2   2  
3          0     3   2  
4          0     2   2

In [47]:
ut=pd.read_csv("Data Collection.csv")

In [48]:
ut.head()

Timestamp        Your Name University Roll No  \
0  2021/11/25 11:20:41 AM GMT+5:30  Naman Chaudhary         1803211033   
1  2021/11/25 11:20:49 AM GMT+5:30   Utsav Mehrotra         1803211058   
2  2021/11/25 11:21:07 AM GMT+5:30     Akshat Atray         1803211003   
3  2021/11/25 11:21:09 AM GMT+5:30    Shivam Sharma      1900321290059   
4  2021/11/25 11:22:16 AM GMT+5:30     Aditya saini      2000321530010   

                                              Branch  Current Year Gender  \
0                                               CEIT             4   Male   
1                                               CEIT             4   Male   
2                                               CEIT             4   Male   
3                                               CEIT             3   Male   
4  Computer Science( CS- AI/ML, CS - Data Science...             2   Male   

   Age Choose your Primary Technology Choose your Secondary Technology  \
0   20                      Front-End                   Cyber Security   
1   21                      Front-End                    Back-End/ API   
2   21                      Front-End                  IoS Development   
3   20                      Front-End                         Database   
4   20                      Front-End              Android Development   

  Primary Programming Language  ... What was your 12th percentage ?  \
0                          C++  ...                       71% - 80%   
1                       Python  ...                       71% - 80%   
2                          C++  ...                       81% - 90%   
3                            C  ...                       81% - 90%   
4                          C++  ...                       81% - 90%   

   What is your B.Tech aggregate SGPA ?  What is your Personality Type ?  \
0                             7.1 - 8.0                                4   
1                             8.1 - 9.0                                3   
2                             8.1 - 9.0                                4   
3                             7.1 - 8.0                                4   
4                             8.1 - 9.0                                4   

  What is your behavior ?  How you take your decisions ?  \
0                        4                             3   
1                        5                             1   
2                        5                             2   
3                        4                             4   
4                        5                             3   

  How easily can you adapt changes ?  Your approach towards life ?  \
0                                  3                             3   
1                                  5                             1   
2                                  5                             2   
3                                  3                             4   
4                                  5                             2   

   Additional Interests.  Are you preparing for any exam ?  \
0              Designing                                No   
1          None of Above                                No   
2                 Sports                                No   
3                 Sports                                No   
4              Designing                              UPSC   

   With what type of person do you want to be in contact ?  
0      Person with same personality traits as yours.        
1      Person with same personality traits as yours.        
2      Person with same personality traits as yours.        
3      Person with same personality traits as yours.        
4      Person with same personality traits as yours.        

[5 rows x 24 columns]

In [49]:
def technical_score(d):
    score=(500*d["ppl"])+(450*d["pt"])++(400*d["c_rate"])+(350*d["spl"])+(300*d["st"])+(250*d["w_rate"])+(200*d["sgpa"])+(150*d["certified"])+(100*d["12"])
    return score

In [50]:
temp=technical.head()

In [51]:
temp

pt  st  ppl  spl  c_rate  w_rate  certified  sgpa  12
0   1   8    1    3       3       3          1     3   3
1   1   2    3    1       3       4          0     2   3
2   1  11    1    3       4       5          1     2   2
3   1   7    2    3       2       3          0     3   2
4   1   6    1    3       3       4          0     2   2

In [53]:
temp["score"]=temp.apply(technical_score,axis=1)

<ipython-input-53-9bea6c31490b>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp["score"]=temp.apply(technical_score,axis=1)


In [54]:
temp

pt  st  ppl  spl  c_rate  w_rate  certified  sgpa  12  score
0   1   8    1    3       3       3          1     3   3   7400
1   1   2    3    1       3       4          0     2   3   5800
2   1  11    1    3       4       5          1     2   2   8900
3   1   7    2    3       2       3          0     3   2   6950
4   1   6    1    3       3       4          0     2   2   6600

In [55]:
technical["score"]=technical.apply(technical_score,axis=1)

<ipython-input-55-9678a7568e6d>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  technical["score"]=technical.apply(technical_score,axis=1)


In [56]:
technical

pt  st  ppl  spl  c_rate  w_rate  certified  sgpa  12  score
0     1   8    1    3       3       3          1     3   3   7400
1     1   2    3    1       3       4          0     2   3   5800
2     1  11    1    3       4       5          1     2   2   8900
3     1   7    2    3       2       3          0     3   2   6950
4     1   6    1    3       3       4          0     2   2   6600
..   ..  ..  ...  ...     ...     ...        ...   ...  ..    ...
323  14   3    2    1       1       1          1     2   2   9950
324  12   5    2    1       3       3          0     3   3  11100
325   1   2    2    3       1       3          0     2   3   4950
326   1   3    2    3       3       2          0     2   2   5700
327   3   1    1    3       2       1          0     1   1   4550

[328 rows x 10 columns]

In [57]:
model3=KMedoids(metric="euclidean", n_clusters=13,  
         init="heuristic", max_iter=2)

In [61]:
from sklearn.cluster import KMeans

In [63]:
Y=np.arange([1,329,1])
kmeans = KMeans(n_clusters=13, random_state=0).fit([Y,technical["score"]])

ValueError: n_samples=1 should be >= n_clusters=13.

In [65]:
Y=np.arange(start=1,stop=329,step=1)

In [77]:
arr=[] 
for i in range(328):
    arr.append((technical["score"][i],Y[i]))
arr=np.array(arr)

In [79]:
kmeans = KMeans(n_clusters=13, random_state=0).fit(arr)

In [80]:
kmeans.labels_

array([12,  9,  7,  6, 10,  2, 10,  9,  1,  2,  7,  6,  2,  2,  5, 11,  7,
        7,  7, 10,  1, 11,  3,  1,  1,  1,  6, 10, 12,  5,  5,  1,  9,  5,
       10, 10,  1,  1,  7, 10,  1, 12,  9,  1,  1,  1,  7,  2, 11,  9, 12,
        8,  6,  5,  5,  9, 10,  7,  9,  2,  3, 12,  9,  2,  4,  2, 12,  1,
        0,  5, 12,  9,  3,  6,  2,  2,  5,  9,  1,  0, 12, 11,  9, 12,  4,
        2, 10,  2,  6, 10, 12,  2,  6,  2,  2,  9,  1,  1, 12,  9,  4, 12,
        5,  9,  0,  5,  7,  9,  7,  7,  9, 12,  3,  9,  1,  6,  5, 10,  1,
        6,  6, 11,  2,  7, 12,  1,  2,  6,  2, 10,  1, 10, 10,  1,  1,  2,
        6,  6,  3, 10,  6,  2,  0,  5,  1,  1,  3,  6,  7,  1,  2,  4,  3,
        7,  5,  1, 12,  0,  2,  2,  1,  5,  2, 10,  9, 10,  2,  2, 10, 10,
        7,  1, 12, 10,  5,  2,  7,  7, 12,  2,  7,  2,  9, 10,  6,  6, 12,
       10, 10,  2,  1,  2,  2, 10, 10, 10,  1,  9,  5,  0, 10,  3, 11,  6,
        3,  7,  8,  7, 12,  6, 10,  7,  6,  9,  6,  5, 10,  2,  5,  9,  9,
        2,  2,  9,  2,  2

In [82]:
kmeans.predict([[5500,200]])

array([9])

In [113]:
def behaviour_score(s):
    st=((350*s["behaviour"])+(300*s["personality"])+(250*s["hobby"])+(200*s["hstudy"])+(150*s["adaptablilty"])+(100*s["decison"])+(50*s["life"]))
    if(s["match"]==0):
        st*=-1  
    return st

In [114]:
behaviour["score"]=behaviour.apply(behaviour_score,axis=1)

<ipython-input-114-f94f0c200f4d>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  behaviour["score"]=behaviour.apply(behaviour_score,axis=1)


In [115]:
behaviour

personality  behaviour  decison  adaptablilty  life  hobby  hstudy  \
0              4          4        3             3     3      4       0   
1              3          5        1             5     5      1       0   
2              4          5        2             5     4      0       0   
3              4          4        4             3     2      0       0   
4              4          5        3             5     4      4       2   
..           ...        ...      ...           ...   ...    ...     ...   
323            4          5        5             4     2      0       0   
324            3          3        3             3     3      1       0   
325            1          4        3             3     3      1       1   
326            3          4        3             3     3      1       0   
327            5          3        1             2     3      0       0   

     match  score  
0        1   4500  
1        1   4000  
2        1   4100  
3        1   3550  
4        1   5600  
..     ...    ...  
323      0  -4150  
324      0  -3100  
325      0  -3050  
326      1   3450  
327      0  -3100  

[328 rows x 9 columns]

In [116]:
arr=[] 
for i in range(328):
    arr.append((technical["score"][i],behaviour["score"][i]))
arr=np.array(arr)

In [117]:
arr

array([[ 7400,  4500],
       [ 5800,  4000],
       [ 8900,  4100],
       [ 6950,  3550],
       [ 6600,  5600],
       [ 6000,  4500],
       [ 6600, -4950],
       [ 5650,  2750],
       [ 8350,  4350],
       [ 6200,  4500],
       [ 8900,  5300],
       [ 6900,  4650],
       [ 6100,  3700],
       [ 6200,  3600],
       [ 5200,  4100],
       [10750,  3700],
       [ 9350,  3500],
       [ 8950,  3600],
       [ 9050,  5100],
       [ 6750, -2850],
       [ 8150, -3600],
       [10600,  5300],
       [ 9750,  3250],
       [ 8400,  4450],
       [ 8350,  2100],
       [ 8150, -3850],
       [ 7000,  3300],
       [ 6700,  3150],
       [ 7500,  1150],
       [ 5000,  2700],
       [ 5150, -3150],
       [ 8150,  4050],
       [ 5550,  3250],
       [ 5050,  4650],
       [ 6700, -3100],
       [ 6600, -2700],
       [ 8750,  3100],
       [ 8650,  3150],
       [ 9400,  3200],
       [ 6450,  5250],
       [ 8600,  2900],
       [ 7950,  5050],
       [ 5350,  4150],
       [ 85

In [118]:
kmeans1 = KMeans(n_clusters=13, random_state=0).fit(arr)

In [119]:
kmeans1.labels_

array([ 0,  7,  0,  5,  7,  7,  4,  2,  0,  7, 10,  7,  2,  2, 12,  3,  9,
        9, 10,  8,  1, 10,  9,  0,  9,  1,  5,  5,  5,  2, 11,  0,  2, 12,
        8,  8,  9,  9,  9,  7,  9,  0, 12,  1,  9,  1,  9,  4, 10,  7,  0,
        6,  5,  2, 12,  2,  8,  1, 11,  2, 10,  5,  2,  2,  6,  7,  0,  1,
       12, 11,  0,  2,  9,  5,  7,  7, 12, 12,  0, 12,  5,  3,  7,  0,  3,
        8,  5,  7,  4,  5,  5,  7,  7,  2,  7, 11,  0,  0,  8,  2,  3,  0,
       11,  4, 12, 12,  9, 11, 10,  9, 12,  8, 10, 11,  0,  5, 11,  4,  9,
        8,  5,  3,  2,  9,  5,  0,  4,  8,  4,  7,  0,  7,  7,  0,  0,  7,
        8,  5,  6,  7,  4,  7, 11, 12,  1,  1, 10,  8,  9,  0,  8,  3, 10,
       10, 11,  9,  1, 12,  4,  2,  0,  2,  7,  7,  4,  5,  2,  2,  7,  5,
        9,  0,  1,  5, 12,  2,  9,  9,  0,  2,  9,  2,  2,  7,  5,  8,  5,
        5,  5,  4,  5,  7,  4,  8,  7,  8,  0, 11, 12, 11,  5,  6,  3,  7,
        9,  1,  3,  1,  5,  7,  7,  1,  5, 11,  4, 11,  7,  2, 12,  2,  2,
        8,  2,  4,  2,  2

In [120]:
kmeans1.predict([[6200,3450]])

array([2])

In [121]:
k_medoids = KMedoids(metric="euclidean", n_clusters=13,  
         init="heuristic", max_iter=2)

In [122]:
k_medoids.fit(arr)

c:\users\utkar\pycharmprojects\pythonproject\venv\lib\site-packages\sklearn_extra\cluster\_k_medoids.py:243: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn(


KMedoids(max_iter=2, n_clusters=13)

In [123]:
k_medoids.labels_

array([11, 12, 10,  5,  9,  9,  6,  4, 11,  9, 11,  9,  8,  8, 12, 10, 10,
       10, 11,  6,  6, 10, 10, 11,  3,  6,  2,  7,  0,  4,  6, 11, 12, 12,
        6,  6, 10,  3, 10,  9,  3, 11, 12,  6,  3,  6, 10,  6, 10,  9,  3,
        6,  5,  4, 12, 12,  6,  6,  6,  4, 10,  3,  4,  4,  6,  9, 11,  6,
       12,  6,  3,  4, 10,  2,  9,  9, 12, 12, 10, 12,  3, 10,  9,  5, 10,
        6,  5,  9,  6,  7,  3,  9,  9,  4,  9,  6, 10,  3,  6,  4, 10, 11,
        6,  6, 12, 12, 10,  6, 10, 10, 12,  6, 10,  6, 11,  1,  6,  6,  3,
        6,  5, 10,  4, 10,  3, 11,  6,  6,  6,  9, 11,  9,  9, 11, 11,  9,
        6,  0,  6,  9,  6,  9,  6, 12,  6,  6, 10,  6, 10, 11,  6, 10, 10,
       11,  6,  3,  6, 12,  6,  4, 11, 12,  9,  8,  6,  7,  8,  4,  9,  7,
       10,  3,  6,  8, 12,  8, 10, 10, 11,  8, 10,  4,  4,  9,  8,  6,  3,
        8,  7,  6,  3,  9,  6,  6,  9,  6, 11,  6, 12,  6,  7,  6, 10,  8,
       10,  6, 10,  6,  3,  9,  9,  6,  5,  6,  6,  6,  9,  4, 12,  4, 12,
        6,  4,  6,  4,  4

In [124]:
k_medoids.predict([[6200,3450]])

array([7], dtype=int64)